name: Release Artifact to Danubetech Nexus

on:
  push:
    branches:
      - 'release-**'
    paths:
      - '.github/workflows/release.yml'

env:
  RELEASE_BRANCH: release-0.2.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ env.RELEASE_BRANCH }}
      - name: Run maven release action
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: ${{ env.RELEASE_BRANCH }}
          git-release-bot-name: "Release Workflow"
          git-release-bot-email: "admin@danubetech.com"

          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

          maven-repo-server-id: danubetech-maven-releases
          maven-repo-server-username: ${{ secrets.MAVEN_USERNAME }}
          maven-repo-server-password: ${{ secrets.MAVEN_PASSWORD }}

          maven-args: "-DreleaseVersion=0.2.0 -DdevelopmentVersion=0.2.1-SNAPSHOT -Dtag=v0.2.0"
